EmmanuelML78/EL-PREDIO

front/src/components/Header/Header.module.css
front/src/components/Home/Home.jsx
front/src/components/Promociones/Promociones.module.css

arregloscss

---

front/src/components/Footer/Footer.module.css
front/src/components/Header/Header.module.css
front/src/components/Nosotros/Nosotros.module.css
front/src/components/Promociones/Promociones.module.css
front/src/index.css

segundoscambioscss

---

front/index.html
front/package.json
front/src/components/Card/Card.jsx
front/src/components/Cards/Cards.jsx

ahora el boton "reservar" de las cards, **si** lleva a la ruta /canchas/id

arreglado link al detail

---

back/src/middlewares/auth.js
back/src/passport/localAuth.js
back/src/routes/userRoute.js

ruta protegida

---

back/src/routes/userRoute.js

GET /me trae los datos del usuario autenticado

rutaMe creada

---

front/src/components/DashBoard/DashBoard.jsx
front/src/redux/actions/authActions.js
front/src/redux/actions/canchaActions.js
front/src/redux/actions/reservaActions.js
front/src/redux/actions/userActions.js
front/src/redux/axiosCfg.js

ahora cada vez que tengan q hacer una peticion axios al back, en vez de hacer:
axios.get("localhost:3001/canchas") (ejemplo)
hacen:
instance.get("canchas")
recuerden importar instance desde /redux/axiosCfg.js

base url configurada para peticiones

---

back/src/routes/userRoute.js
front/src/components/CreadorCanchas/CreadorCanchas.jsx
front/src/components/Profile/Profile.css
front/src/components/Profile/Profile.jsx
front/src/redux/actions/authActions.js

Imagen en perfil y cambios en la ruta .put de /me

image para perfil

---

back/src/controllers/ReservaControllers.js
front/src/App.jsx
front/src/components/DashBoard/DashBoard.jsx
front/src/components/Detail/Detail.jsx
front/src/components/Error401/Error401.jsx
front/src/components/Header/Header.jsx
front/src/components/Home/Home.jsx
front/src/components/Landing/Landing.jsx
front/src/components/MisReservas/MisReservas.jsx
front/src/components/Navbar/Navbar.jsx
front/src/components/Navbar/Navbar.module.css
front/src/redux/actions/authActions.js
front/src/redux/actions/canchaActions.js
front/src/redux/actions/reservaActions.js
front/src/redux/actions/userActions.js
front/src/redux/reducer/reservasReducer.js

1. vista para invitado (no logeado) tiene su propia nav/header y home
2. ya no se usa (creo que lo saque en todas) el error401, directamente redirecciona al login que ahora esta en /login
3. el home esta en "/" y en "/home"
4. añadida en front auth con google, funciona el boton y las validaciones
5. añadidas validaciones desde las actions
6. modificada la action de reserva, se llevo la funcionalidad de la data de la reserva del front al back
7. modificaciones en estilos, iconos, y detalles en general
8. eliminadas actions inutiles/sin funcionalidad
9. el form de registro ya no permite espacios en nombre/apellido (no los permitia originalmente, pero ahora directamente no deja escribirlos (.trim()))

home/nav/header para guests, fix pasarela, etc

---

back/src/middlewares/auth.js
back/src/routes/userRoute.js

Cree la ruta logout para cerrar sesión con google y demás modifique el middleware de admin para que acepte también a los usuarios autenticados mediatante terceros

Ruta logout

---

back/src/routes/canchaRoutes.js
back/src/routes/userRoute.js
front/package.json
front/src/components/ReservasTable/ReservasTable.jsx
front/src/components/UsersTable/UsersTable.jsx
front/src/redux/actions/userActions.js
front/src/redux/reducer/userReducer.js

1. se pueden eliminar usuarios
2. se pueden filtrar usuarios por nombre y apellido (juntos)
3. se pueden filtrar usuarios por estado (todos/activo/inactivo)
4. se pueden ordenar usuarios por fecha de registro (asc/desc)
5. se añadió una libreria de alertas (como toastify pero se le puede poner Aceptar/Cancelar y ejecuta codigo en base a la opcion), la use para confirmar la eliminacion del usuario @spawn22 podrias usarla para reemplazar el window.alert de deleteCanchas

delete users + filtros

---

back/src/controllers/ReviewsControllers.js
back/src/routes/reviewRoute.js
front/src/components/CreadorReviews/CreadorReviews.jsx
front/src/components/Reviews/Reviews.jsx
front/src/redux/actions/reservaActions.js
front/src/redux/actions/reviewsActions.js

rutas review arreglado y front arreglado

reviews de usuario

---

back/src/models/User.js
back/src/routes/authRoute.js

Falta crear la funcion que envie el mail al user

ruta recuperar password hecho

---

back/src/passport/googleAuth.js
back/src/routes/authRoute.js

Algunos arreglos

---

back/src/controllers/ReservaControllers.js
front/src/components/CreadorCanchas/CreadorCanchas.jsx
front/src/components/MisReservas/MisReservas.jsx
front/src/components/ReservasTable/ReservasTable.jsx
front/src/components/ReservasTable/ReservasTable.module.css
front/src/components/UsersTable/UsersTable.jsx
front/src/redux/actions/reservaActions.js

filtros de reservas

---

back/src/db.js
back/src/models/Promotion.js

cree el modelo Promotion y establecí las relaciones con Cancha.

modelo creado

---

back/src/controllers/promoController.js
back/src/routes/index.js
back/src/routes/promoRoute.js

rutas creadas

---

back/src/controllers/ReservaControllers.js
front/src/components/ReservasTable/ReservasTable.jsx
front/src/redux/actions/reservaActions.js

tuve que hacer un fix en el back para que funcione

admin puede editar estado de una reserva

---

back/src/controllers/ReservaControllers.js
back/src/routes/reservaRoute.js

algunos cambios

---

back/src/controllers/ReservaControllers.js
back/src/middlewares/auth.js
back/src/models/Reserva.js
front/src/App.jsx

camios pequeños

---

front/src/components/Oportunidades/Oportunidades.jsx

dialogos front
